[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'natebosch/vim-lsc'
hook_add = 'let g:lsp_async_completion = 1'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
      \ "colorscheme": "wombat"
      \ }
  set noshowmode
'''


# colorschemes
[[plugins]]
repo = 'raphamorim/lucario'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

